// Server entry point
// const { DBConfig } = require('./config/DBConfig');
//make a get request to the external server/api/auth
const axios = require('axios');
const express = require('express');
const cors = require('cors');
const app = express();
app.use(cors());
const { PORT, EXTERNAL_SERVER_URL } = require('./config/Env');

async function main() {
    try {
        // Connect to MongoDB
        // await DBConfig.connectDB();
        // console.log('Connected to MongoDB');
        const autoGeneratedHeaders ={
            'Content-Type': 'application/json',
            
        }
        const link = `${EXTERNAL_SERVER_URL}/api/auth`
        console.log('link:', link);
        // Make a request to the external server
        const response = await axios.get(link, {
            headers: autoGeneratedHeaders,
        });
        console.log('External server response:', response.data);
    } catch (error) {
        console.error('Failed to connect to the external server:', error.message);
    }
    
    app.listen(PORT, () => {
        console.log(`Server is running on http://localhost:${PORT}`);
    });
    }

    main();
